---
apiVersion: v1
kind: Service
metadata:
    name: my-nginx
    labels:
        run: my-nginx
spec:
    selector:
        run: my-nginx
    type: ClusterIP
    ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
