apiVersion: v1
kind: Pod
metadata:
  name: robot
  namespace: office
spec:
  serviceAccountName: robot
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ['/bin/bash', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']