kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: robot-binding
  namespace: office
subjects:
- kind: ServiceAccount
  name: robot
  apiGroup: ""
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""
