kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: robot-binding
  namespace: office
subjects:
- kind: ServiceAccount
  name: robot
roleRef:
  kind: Role
  name: deployment-manager # we are reusing the previously created Role
  apiGroup: rbac.authorization.k8s.io
